function vec = gen_edt_vec(edit, codebook)
%=============================================================
%Input:
%           edit                    A n x d matrix represent an editorial
%           codebook           A k x d matrix represent a codebook generated by AK-means
%Output:
%           vec                    A k dimensional vector represent the editorial
%=============================================================

dir_yael = './yael/';
addpath ([dir_yael '/matlab']);

edit = edit';
% codebook = codebook';
n = size (edit, 2);          % number of descriptors
k = size (codebook, 2);  % number of centroids

% find the nearest neigbhors for each descriptor
[idx, ~] = yael_nn (codebook, edit);
vec = zeros (1, k);
for i = 1:n
  vec (idx(i)) = vec(idx(i)) + 1;
end
vec = yael_fvecs_normalize (vec);